name: flutter_file_view_example
description: Demonstrates how to use the flutter_file_view plugin.

publish_to: 'none'

version: 1.3.0+19

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.28

  flutter_file_view:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/files/
