name: flutter_file_view
description: File viewer plugin for Flutter, support local file and network link of Android, iOS.
version: 1.3.0+1
homepage: https://github.com/LiWenHui96/flutter_file_view

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.file.view
        pluginClass: FlutterFileViewPlugin
      ios:
        pluginClass: FlutterFileViewPlugin

  assets:
    - assets/images/
